# This is a basic workflow to help you get started with Actions

name: GoodNew Data Scrape

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    # at 00:00 hrs everyday
    - cron: '0 0 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger our build webhook to get New NewsItems
      run: curl -d '{"urlList":["https://www.goodnewsnetwork.org","https://www.positive.news"]}' -H "Content-Type:application/json" -X POST https://goodnews-app.herokuapp.com/api/news/scrape
